#!/bin/bash
if [ `hostname` == "kona" ]; then
    echo kona
    export MATLAB_PATH=/vol/tools/Mathworks/Matlab/R2012b
    PLATFORM=lin64
    export XILINX_PATH=/vol/tools/Xilinx/14.7/ISE_DS
    export MLIB_DEVEL_PATH=/home/mwang/Apps/mlib_devel_jack
    export TMP=/home/mwang/Tmp
    export TEMP=/home/mwang/Tmp
    export DSP_CACHE_DIR=/home/mwang/Tmp
    #############################################
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    cd $DIR
    source $XILINX_PATH/settings64.sh
    export PATH=${PATH}:${XILINX}/ISE/bin/${PLATFORM}:${XILINX_PATH}/ISE/sysgen/bin/${PLATFORM}
    export XPS_BASE_PATH=$MLIB_DEVEL_PATH/xps_base
    export MATLAB=$MATLAB_PATH
    $MATLAB/bin/matlab
elif [ `hostname` == "casr99" ]; then
    echo casr99

else
    echo "unkown host"
fi
